accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('change-password/', views.My_password_change.as_view(),
         name='password-change-view'),
    path('change-password/done/', views.My_password_reset_done.as_view(),
         name='password-change-done-view'),
    
]

link2class/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

# from accounts import views as account_view
from . import views
from django.urls import path, include

urlpatterns = [
    path('',views.home, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('benifits/',include('training_center.benifits.urls'),name='const'),
    path('healthcare/',include('training_center.healthcare.urls'),name='healthcare'),
    path('career/',include('training_center.career.urls'),name='info_tech'),
    path('familysupport/',include('training_center.familysupport.urls'),name='manufacturing'),
    path('peer2peer/',include('training_center.peer2peer.urls'),name='marketing'),
    path('transition/',include('training_center.transition.urls'),name='trans'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
         template_name='accounts/password_reset.html'), name='password_reset'),
    path('msg/',views.message_send, name='msg_sent'),         
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done_forget.html'), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    
    path('admin/', admin.site.urls),


]
if settings.DEBUG: 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Link2Class Dashboard'
admin.site.site_title = "Admin Portal"
admin.site.index_title = 'Link2Class Administration'

accounts/models.py
from django.contrib.auth.models import AbstractUser, AbstractBaseUser, PermissionsMixin
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.sessions.models import Session
import datetime
from django.core.cache import cache
from django.conf import settings
from PIL import Image


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, first_name, phone, password, **extra_fields):
        values = [email, first_name, phone]
        field_value_map = dict(zip(self.model.REQUIRED_FIELDS, values))
        for field_name, value in field_value_map.items():
            if not value:
                raise ValueError('The {} value must be set'.format(field_name))

        email = self.normalize_email(email)
        user = self.model(
            email=email,
            first_name=first_name,
            phone=phone,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = None
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    phone = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    organization = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    share_my_contact = models.BooleanField(default=False,null=True,blank=True)
    update_through_email = models.BooleanField(default=False,null=True,blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    current_status = models.CharField(max_length=50,null=True)
    date_of_seperation = models.DateTimeField(null=True)
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', ]

    objects = CustomUserManager()

    def __str__(self):
        return self.first_name

    def get_all_logged_in_users(self):
        user = (x for x in CustomUser.objects.all())
        return user


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    state = models.CharField(max_length=150)
    zip_code = models.CharField(max_length=150)
    image = models.ImageField(
        default='avatar-icon.png', upload_to='media/profile_pics')

    def __str__(self):
        return f'{self.first_name} Profile'

    def last_seen(self):
        return cache.get('seen_%s' % self.user.first_name)

    def online(self):
        if self.last_seen():
            now = datetime.datetime.now()
            if now > self.last_seen() + datetime.timedelta(
                         seconds=settings.USER_ONLINE_TIMEOUT):
                return False
            else:
                return True
        else:
            return False








def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(
            user=instance,first_name=instance.first_name, last_name=instance.last_name, phone=instance.phone, email=instance.email)

post_save.connect(create_profile, sender=CustomUser)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, CustomUser
import math
from django.contrib.auth import get_user_model

User = get_user_model()


class LoginForm(forms.Form):
    email = forms.CharField(label="",widget=forms.TextInput(attrs={"class":"form-control","id":"login_mail"}))
    password = forms.CharField(label="",widget=forms.PasswordInput(attrs={"class":"form-control","id":"login_password"}))


class RegisterForm(forms.Form):
    STATUS_CHOICES = (
        ('','Status'),
        ('active duty','Active Duty'),
        ('guard/reserve','Gurad/Reserve'),
        ('veteran','Veteran'),
        ('retired','Retired'),
        ('spouse','Spouse'),
    )
    ORGANIZATION_CHOICES = (
        ('','Organization'),
        ('air force','Air Force'),
        ('army','Army'),
        ('coast guard','Coast Guard'),
        ('marine corps','Marine Corps'),
        ('navy','Navy'),
    )
    RANK_CHOICES = (
        ('','Rank'),
        ('e1','E-1'),
        ('e2','E-2'),
        ('e3','E-3'),
        ('e4','E-4'),
        ('e5','E-5'),
        ('e6','E-6'),
        ('e7','E-7'),
        ('e8','E-8'),
        ('e9','E-9'),
    )

    first_name = forms.CharField(label="",widget=forms.TextInput(attrs={"class":"form-control","placeholder":"First Name","id":"reg_first_name"}))
    last_name = forms.CharField(label="",widget=forms.TextInput(attrs={"class":"form-control","placeholder":"Last Name","id":"reg_last_name"}))
    email = forms.EmailField(label="",widget=forms.EmailInput(attrs={"class":"form-control","placeholder":"Email","id":"reg_email"}))
    password = forms.CharField(label="",widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Password","id":"reg_password"}))
    password2 = forms.CharField(label="", widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Confirm Password","id":"reg_password2"}))
    organization = forms.ChoiceField(label="",choices = ORGANIZATION_CHOICES)
    rank = forms.ChoiceField(label="",choices = RANK_CHOICES)
    current_status = forms.ChoiceField(label="",choices = STATUS_CHOICES)
    date_of_sepration = forms.DateField(widget=forms.DateInput(attrs={"class":"form-control",'type': 'date'}))
    phone = forms.CharField(label="",widget=forms.TextInput(attrs={"class":"form-control","placeholder":"Mobile Number","id":"reg_phone"}))
    share_my_contact = forms.BooleanField(required=False,widget=forms.CheckboxInput())
    update_through_email = forms.BooleanField(required=False,widget=forms.CheckboxInput())

    def clean(self):
        data = self.cleaned_data
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password2 != password:
            raise forms.ValidationError('Password Does not match!!')
        return data   
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = CustomUser.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError('Email is Taken')
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if len(phone)<10 and math.isnan(phone):
            raise forms.ValidationError("Phone should be a 10 digit number.")
        return phone



class ProfileUpdateForm(forms.ModelForm):
    address = forms.CharField(required=False, max_length=500)
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'address','state','city','zip_code', 'phone', 'image']
        # widgets = {
        #     'email': forms.EmailInput(attrs={'class': 'form-control', 'readonly': True}),
        # }


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'phone']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout,get_user_model
from django.contrib.auth import login as auth_login
from django.contrib import messages
from .models import CustomUser, Profile
from django.http import JsonResponse
from django.core import serializers
from django.contrib.auth.views import PasswordChangeView, PasswordResetDoneView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .forms import  LoginForm, RegisterForm, ProfileUpdateForm, UserUpdateForm

# Create your views here.
User = get_user_model()

def login(request):
    form =  LoginForm(request.POST or None)
    form_r =  RegisterForm(request.POST or None)
    context = {
        'form':form,
        'form_r':form_r,
    }
    if form.is_valid():
        # form = form.save(commit=False)
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('/')
        else:
            return JsonResponse({"error": form.errors}, status=400)
    else:
        return render(request, 'accounts/login.html', context)


def register(request):
    form_r =  RegisterForm(request.POST or None)
    context = {
        'form':form_r
    }
    if form_r.is_valid():
        # form_r = form_r.save(commit=False)
        first_name = form_r.cleaned_data.get('first_name')
        last_name = form_r.cleaned_data.get('last_name')
        email = form_r.cleaned_data.get('email')
        organization = form_r.cleaned_data.get('organization')
        title = form_r.cleaned_data.get('title')
        phone = form_r.cleaned_data.get('phone')
        share_my_contact = form_r.cleaned_data.get('share_my_contact')
        update_through_email = form_r.cleaned_data.get('update_through_email')
        password = form_r.cleaned_data.get('password')
        password2 = form_r.cleaned_data.get('password2')
        new_user = CustomUser.objects.create_user(first_name=first_name,last_name=last_name,phone=phone,email=email,organization=organization,title=title,share_my_contact=share_my_contact,update_through_email=update_through_email,password=password)
        new_user.save()
        auth_login(request,new_user)
        return redirect('/')
        
    return render(request, 'accounts/register.html',context)


@login_required
def logout(request):
    logout(request)
    return redirect("/")


class My_password_change(PasswordChangeView):
    template_name = 'training_center/home.html'
    success_url = reverse_lazy('accounts:password-change-done-view')


class My_password_reset_done(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="vw-100 vh-100" style="background-image: url({% static '/img/Main_login_screen.png' %}); background-size: 100% 100%;">
    <form method="POST" class="mb-3" id="login-form">{% csrf_token %}
        {{form.as_p}}
        <button type="submit" id="login_btn"></button>
    </form>
    <a href="{% url 'password_reset' %}">
      <div class="wrapper" id="forgot_pass"></div>
    </a>
    <a href="{% url 'accounts:signup' %}" class="">
        <div class="wrapper" id="create_account"></div>
    </a>
    <a href="#">
      <div class="wrapper" id="login_help"></div>
    </a>
</div>
<!-- <div class="modal fade" id="signup_modal" tabindex="-1" role="dialog" aria-labelledby="signup_modal" aria-hidden="true" data-backdrop="static">
      <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl" role="document">
        <div class="modal-content">
          <div class="modal-header text-white py-1 px-2">
            <h5 class="modal-title " id="whoshere_modal_title">Signup</h5>
            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body p-0" style="min-height: 60vh; background-color: #eee;">
            <div style="border: 1p solid white;" class="mt-2">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-12 col-sm-6">
                        <form method="POST" id="register-form" class="mb-3">{% csrf_token %}
                            {{form_r.as_p}}
                            <input type="submit" class='btn btn-success btn-block' />
                        </form>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div> -->
{% endblock content %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Password-Change
{% endblock title %}
{% block content %}

<div class="container mt-5" style="margin-top:150px !important;">
    <div class="card p-3 m-5 border border-primary">
        <div class="card-body">
            <form method="POST" >
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary">Change</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Password-reset
{% endblock %}
{% block content %}
<div class="container" style='margin-top:100px;'>
    <div class="card p-3 text-center">
        <legend class="border-bottom mb-4">Reset Password</legend>
        <form method="POST" class='col-6 offset-3'>
            {% csrf_token %}
            <fieldset class="form-group p-5">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button> 
                <a class="btn btn-outline-info" href="/">Back</a> 
            </div>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}
{% load static %}
{% block title %}
Password-reset-confirm
{% endblock %}
{% block content %}
<div class="container" style='margin-top:100px;'>
<div class="card p-3 text-center">
    <div class="alert alert-info">
        Your Password has been ReSet.
    </div>
    <a href="{% url 'accounts:login' %}">Sign In Here</a>
</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Password-reset-confirm
{% endblock %}
{% block content %}

{% if validlink %}
<div class="container" style='margin-top:100px;'>
<div class="card p-3 text-center">
    <legend class="border-bottom mb-4">Reset Password</legend>
    <form method="POST" class='col-6 offset-3'>
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button> 
            </div>
        </form>
{% else %}
<div class="card p-5 mt-5 text-center">
    <p class="alert alert-danger">
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
</div>
  {% endif %}
</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Password-reset-done
{% endblock %}
{% block content %}
<div class="container" style='margin-top:100px;'>
<div class="card p-3 text-center">
    <h1 class='display-4'>Password has been changed!!</h1>
    <a href="{% url 'home' %}"> <button class="btn btn-primary">Home</button></a>
</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done_forget.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}
{% load static %}
{% block title %}
Password-reset-done
{% endblock %}
{% block content %}
<div class="container" style='margin-top:100px;'>

    <div class="alert alert-info">
        An email has been sent with instructions to reset your password.
        Please Close this window and Check your Email and go to that link.
        Please Check The mail in Spam also, if not found.
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if error %}
    {{ error }}
{% endif %}
<div class="mt-5" style="">
    <div class="container">
        <h1 class='text-center text-white'>Signup Form</h1>
        <div class="row">
            <div class="col-6 offset-3">
            <form method="POST" class="mb-3" id="register-form">{% csrf_token %}
                {{form|crispy}}
                <input type="submit" class='btn btn-success btn-block' />
            </form>
            <div class="border-top pt-3 mb-4">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{% url 'accounts:login' %}">Sign In</a>
                </small>
            </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}