accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('change-password/', views.My_password_change.as_view(),
         name='password-change-view'),
    path('change-password/done/', views.My_password_reset_done.as_view(),
         name='password-change-done-view'),
    
]

link2class/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

# from accounts import views as account_view
from . import views
from django.urls import path, include

urlpatterns = [
    path('',views.home, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('benifits/',include('training_center.benifits.urls'),name='const'),
    path('healthcare/',include('training_center.healthcare.urls'),name='healthcare'),
    path('career/',include('training_center.career.urls'),name='info_tech'),
    path('familysupport/',include('training_center.familysupport.urls'),name='manufacturing'),
    path('peer2peer/',include('training_center.peer2peer.urls'),name='marketing'),
    path('transition/',include('training_center.transition.urls'),name='trans'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
         template_name='accounts/password_reset.html'), name='password_reset'),
    path('msg/',views.message_send, name='msg_sent'),         
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done_forget.html'), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    
    path('admin/', admin.site.urls),


]
if settings.DEBUG: 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Link2Class Dashboard'
admin.site.site_title = "Admin Portal"
admin.site.index_title = 'Link2Class Administration'

training_center/benifits/urls.py
from .views import (
    manufacturing,
    todays_events_view, 
    upcoming_events_view, 
    ondemand_events_view,
    like_unlike_post
)
from django.urls import path

app_name = 'manufacturing'

urlpatterns = [
    path('',manufacturing, name='manufacturing'),
    path('today/<pk>/',todays_events_view, name='todays_events'),
    path('upcoming/<pk>/',upcoming_events_view, name='upcoming_events'),
    path('ondemand/<pk>/',ondemand_events_view, name='ondemand_events'),
    path('liked/', like_unlike_post, name='like-post-view'),
]

training_center/career/urls.py
from .views import (
    information_tech,
    todays_events_view, 
    upcoming_events_view, 
    ondemand_events_view,
    like_unlike_post_career
)
from django.urls import path

app_name = 'info_tech'

urlpatterns = [
    path('',information_tech, name='it'),
    path('today/<pk>/',todays_events_view, name='todays_events'),
    path('upcoming/<pk>/',upcoming_events_view, name='upcoming_events'),
    path('ondemand/<pk>/',ondemand_events_view, name='ondemand_events'),
    path('liked/', like_unlike_post_career, name='like-post-view'),
]

training_center/healthcare/urls.py
from .views import (
    health_and_medicine,
    todays_events_view, 
    upcoming_events_view, 
    ondemand_events_view,
    like_unlike_post_health
)
from django.urls import path

app_name = 'healthcare'

urlpatterns = [
    path('',health_and_medicine, name='health'),
    path('today/<pk>/',todays_events_view, name='todays_events'),
    path('upcoming/<pk>/',upcoming_events_view, name='upcoming_events'),
    path('ondemand/<pk>/',ondemand_events_view, name='ondemand_events'),
    path('liked/', like_unlike_post_health, name='like-post-view'),

]

training_center/peer2peer/urls.py
from .views import (
    marketing,
    todays_events_view, 
    upcoming_events_view, 
    ondemand_events_view,
    like_unlike_post_peer2peer
)
from django.urls import path

app_name = 'marketing'

urlpatterns = [
    path('',marketing, name='marketing'),
    path('liked/', like_unlike_post_peer2peer, name='like-post-view'),
    # path('today/<pk>/',todays_events_view, name='todays_events'),
    # path('upcoming/<pk>/',upcoming_events_view, name='upcoming_events'),
    # path('ondemand/<pk>/',ondemand_events_view, name='ondemand_events'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Link2Class</title>
    {% include 'base/css.html' %}
    
    {% block base_head %}{% endblock %} 

  </head>
  <body>

  
  {% block content %}

  {% endblock %}
  

  {% include 'base/js.html' %}
{% block script %}{% endblock script%}
 
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block base_head %}

{% endblock %}

{% block content %}
    <div class="min-vh-100 w-100" id="home_bg">
      <a href="{% url 'const:const' %}">
        <div class="wrapper" id="top_left"></div>
      </a>
      <a href="{% url 'info_tech:it' %}">
        <div class="wrapper" id="top_center"></div>
      </a>
      <a href="{% url 'manufacturing:manufacturing' %}">
        <div class="wrapper" id="top_right"></div>
      </a>
      <a href="{% url 'healthcare:health' %}">
        <div class="wrapper" id="bottom_left"></div>
      </a>
      <a href="{% url 'marketing:marketing' %}">
        <div class="wrapper" id="bottom_center"></div>
      </a>
      <a href="{% url 'trans:trans' %}">
        <div class="wrapper" id="bottom_right"></div>
      </a>

      <a href="/">
        <div class="wrapper" id="home_lobby"></div>
      </a>
      <a href="#">
        <div class="wrapper" id="home_favourites"></div>
      </a>
      <a href="#">
        <div class="wrapper" id="home_transcripts"></div>
      </a>
      <a href="#">
        <div class="wrapper" id="home_map"></div>
      </a>
      <a href="#">
        <div class="wrapper" id="home_search"></div>
      </a>
      <a href="#" data-toggle="modal" data-target="#profile_modal">
        <div class="wrapper" id="home_profile"></div>
      </a>
      <a href="#" class="" data-toggle="modal" data-target="#whoshere_modal">
        <div class="wrapper" id="home_who"></div>
      </a>
      <a href="#">
        <div class="wrapper" id="home_forum"></div>
      </a>
      <a href="#">
        <div class="wrapper" id="home_help"></div>
      </a>
      <a href="{% url 'logout' %}">
        <div class="wrapper" id="home_logout"></div>
      </a>
    </div>
    {% include 'training_center/snippets/who.html' %}
    {% include 'training_center/snippets/profile.html' %}

{% endblock content %}